---
title: "9 September 18"
author: ~
date: '2018-09-09'
slug: 9-sep-18
categories: []
tags: []
highlight: "kate"
description: "'Are you a gardener or a flower? In every relationship, you're either a gardener or a flower. I'm a gardener that wants to be a flower, how fucked up am I?' - LaVona"
screencap: "E13"
edition: "9 Setember 18"
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(highcharter)
library(radarchart)
library(yaml)
library(shiny)
library(purrr)
library(glue)
library(reactable)
library(tidyverse)

source("R/film-review-utils.R")
       
# Load Edition YAML
yaml = yaml.load_file("yaml/edition-13.yaml")

# Edition
ed = yaml$edition
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
yaml %>%
pluck("reviews") %>%
keep(~!is.null(.$reviewer)) %>%
map(compile_review, edition = ed) %>% 
tagList()
```

## Other films we watched

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
yaml %>%
  pluck("reviews") %>%
  keep(~is.null(.$reviewer)) %>%
  compile_ratings()
```