baseURL = "/"
languageCode = "en-us"
title = "Tom Bishop"
theme = "kube"
description = "A place to store my thoughts."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Tom Bishop" # add your company name
  github = "TMBish" # add your github profile name
  twitter = "bigbishdog" # add your twitter profile
  email = "tomwbish@gmail.com"


[[menu.main]]
    name = "About Me"
    weight = -100
    url = "/aboutme/"
[[menu.main]]
    name = "Shiny"
    weight = -100
    url = "/shiny/"
[[menu.main]]
    name = "Lab"
    weight = -100
    url = "/lab/"