---
title: "All Reviews & Ratings"
author: ~
date: '2100-01-01'
slug: all-reviews
categories: []
tags: []
highlight: "kate"
description: "All our reviews and ratings in one place."
screencap: "ALL"
edition: "All Ratings"
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(highcharter)
library(radarchart)
library(yaml)
library(shiny)
library(purrr)
library(glue)
library(reactable)
library(tidyverse)
library(htmltools)

source("R/film-review-utils.R")
#source("content/films/R/film-review-utils.R")

#df = read_csv("D:/googledrive/Tom and Hannah/Movies/reviews.csv")
df = read_csv("C:/Users/tomwb/Desktop/reviews.csv")


oamd_search = function(title, year) {
  
  endpoint = 
    glue("http://www.omdbapi.com/?t={title}&y={year}&apikey=309178b8") %>%
    URLencode()
  
  meta = 
    httr::GET(endpoint) %>%
    httr::content(type = "application/json") %>%
    tibble::as_tibble() %>%
    nest(Ratings = Ratings) %>%
    mutate(Ratings = Ratings %>% map(~as_tibble(.) %>% unnest_wider(Ratings))) %>%
    mutate(
      rotten_tomatoes = 
        Ratings %>% 
        map(
          ~filter(., Source=="Rotten Tomatoes")
        )
    ) %>%
    unnest_wider(rotten_tomatoes) %>%
    janitor::clean_names() 
  
  meta %>%
    select(runtime, value, img_url = poster, imdb = imdb_rating, rotten_tomatoes = value, director, actors, plot, box_office)

}


# Get Images From Open Movies
df =
  df %>%
  mutate(
    omdb_metadata = 
      pmap(
        .l = list(title, year),
        .f = possibly(oamd_search, otherwise = NULL)
      )
  ) %>%
  unnest_wider(omdb_metadata)

```


```{r echo=FALSE, warning=FALSE, message=FALSE}

rt_input = 
  df %>%
  # select(
  #   -review_text, -pick_of_the_week, -acting, -story, 
  #   -dialogue, -entertainment, -cinematography, -image, 
  #   -reviewer, -edition, -similar_film
  # ) %>%
  select(img_url, title, year, genre, runtime, rotten_tomatoes, imdb, tom, hannah) %>%
  mutate(
    genre = genre %>% str_to_lower(),
    rotten_tomatoes = rotten_tomatoes %>% str_remove("%") %>% as.numeric(),
    imdb = imdb %>% as.numeric(),
    runtime = runtime %>% str_remove(" min") %>% as.numeric()
  ) 

rt_input %>%
reactable(
  # Options
  # ___________
  compact = FALSE,
  class = "other-films",
  # Column Groups
   columnGroups = list(
    colGroup(name = "Info", columns = c("title", "year", "genre", "runtime")),
    colGroup(name = "Critic Ratings", columns = c("imdb", "rotten_tomatoes")),
    colGroup(name = "Our Ratings", columns = c("tom", "hannah"))
  ),
  # Pagination
  showPageSizeOptions = TRUE, 
  pageSizeOptions = c(20, 50), 
  defaultPageSize = 20,
  pagination = TRUE,
  paginationType = "simple",
  # Searching
  searchable = TRUE,
  defaultColDef = colDef(
    headerClass = "other-films-header", 
    align = "center",
    footerStyle = list(fontWeight = "bold")
  ),
  
  # Column Definitions
  # ___________
  columns = list(
    img_url = colDef(
        name = "",
        cell = function(value, index) {
          div(
            img(style = "height: 142px; width: 100px", class = "flag", alt = "", src = value)
          )
        }
    ),
    runtime = colDef(
      name = "Run Time",
      cell = function(value) {
        value %>% str_c(" mins")
      }
    ),
    genre = colDef(
      name = "Genre",
      cell = function(value) {
        htmltools::span(class = "label upper outline warning", value)
      }  
    ),
    year = colDef(name = "Year"),
    title = colDef(name = "Title"),
    imdb = colDef(name = "IMDB"),
    rotten_tomatoes = colDef(
      name = "Rotten Tomatoes", 
      cell = function(value) {
        case_when(
          is.na(value) ~ "-",
          TRUE ~ value %>% str_c("%")

        )
      }
    ),
    tom = colDef(
      name = "Tom", 
      cell=function(value) {
        p(style = "font-size: 18px",
          span(style = "color: #F7C919; font-weight: bold", value), 
          span(style = "color: rgba(0, 0, 0, 0.1); font-weight: bold", " / 10")
        )
      } 
    ),
    hannah = colDef(
      name = "Hannah", 
      cell=function(value) {
        p(style = "font-size: 18px",
          span(style = "color: #F7C919; font-weight: bold", value), 
          span(style = "color: rgba(0, 0, 0, 0.1); font-weight: bold", " / 10")
        )
      } 
    )
  ),
  
  # Row Detail
  # ___________
  details = function(index) {
    
    
    film = df[index, ]

    
    # Feild 
    film_detail_field = function(name, value) {
      if (is.na(value)) {
        NULL
      } else {
        tagList(
          div(class = "film-detail-name", name), 
          value
        )
      }
    }
    
    detail = 
      div(
        class = "film-detail",
                 
        # Details Header
        div(
          class = "film-detail-header",
          film$title,
          span(
            class = "film-detail-name", 
            str_c("  ", film$year)
          )
        ),
        
        # Details
        film_detail_field("Plot", film$plot),
        
        # Review
        film_detail_field(
          
          glue("Our Review [{str_to_upper(film$reviewer)}]"), film$review_text
          
          # markdown::markdownToHTML(
          #   text = if(is.na(film$review_text)) "" else film$review_text, 
          #   fragment.only = TRUE
          # ) %>% 
          # htmltools::HTML()
          
        ),
        
        # Components
        film_detail_field(
          "Our Rating Components",
          
          reactable(
              film %>% 
              select(acting, dialogue, story, entertainment, cinematography) %>%
              pivot_longer(everything(), names_to = "Component", values_to = "Score") %>%
              mutate(Component = str_to_title(Component))
            ,
            pagination = FALSE,
            defaultColDef = colDef(headerClass = "film-detail-components-header",  align = "right"),
            fullWidth = FALSE,
            class = "film-detail-components"
          )
          
        ),
        
        # Director
        film_detail_field("Director", film$director),
        
        # Actors
        film_detail_field("Actors", film$actors),
        
        # Box Office
        film_detail_field("Box Office", film$box_office)
        
    )

    detail
    
  }
)



```